### ISSUE TITLE
tmux_2.0-3_amd64.deb artık yok

### ISSUE THREAD

**Issue by salihozd** [pivotus/glove#5]
```
--2015-10-31 21:11:09--  http://ftp.de.debian.org/debian/pool/main/t/tmux/tmux_2.0-3_amd64.deb
ftp.de.debian.org (ftp.de.debian.org) çözümleniyor... 141.76.2.4
ftp.de.debian.org (ftp.de.debian.org)[141.76.2.4]:80 bağlanılıyor... bağlantı kuruldu.
HTTP isteği gönderildi, cevap bekleniyor... 404 Not Found
2015-10-31 21:11:09 HATA 404: Not Found.
```

Gibi bir hata alıyorum. Adrese tarayıcıdan girdim, ilgili versiyonun `tmux_2.0-3~bpo8+1_amd64.deb` şeklinde bir paketi var. Bu paket `30-May-2015` tarihinde eklenmiş/değiştirilmiş.

Kendi bilgisayarım için adı değişen paketle deneme yapıyorum, döneceğim.

**Comment by salihozd** [comment]
`tmux_2.0-3~bpo8+1_amd64.deb` ile sorun yaşamadım.

**Comment by ecylmz** [comment]
Ubuntu'nun yeni sürümlerinde tmux'ın daha yeni versiyonları geldiğinden, elle tmux'ı kurmaya gerek kalmadı. ilgili betikten tmux kurma satırı kaldırıldı.
